name: manual update Docker image on Ibf training 

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ibf-typhoon-PAGASA


jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    env:
      TZ: Etc
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2       
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT_TRAINING }}
          username: ${{ secrets.ACR_USERNAME_TRAINING }}
          password: ${{ secrets.ACR_PASSWORD_TRAINING }}
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.ACR_ENDPOINT_TRAINING }}/${{ env.IMAGE_NAME }}:v1
